### ISSUE TITLE
Error when deploying

### ISSUE THREAD

**Issue by PresentMonkey** [r-spacex/SpaceXLaunchBot#9]
When trying to deploy a python TypeError occurs. Below is the log.

`2020-05-27 12:30:10,218 : INFO : discordclient : __init__ : Client initialised
Traceback (most recent call last):
  File "./spacexlaunchbot/main.py", line 15, in <module>
    main()
  File "./spacexlaunchbot/main.py", line 10, in main
    client = discordclient.SpaceXLaunchBotClient()
  File "/opt/SpaceXLaunchBot/spacexlaunchbot/discordclient.py", line 25, in __init__
    self.loop.add_signal_handler(signal.SIGTERM, self.shutdown)
  File "/usr/local/lib/python3.8/asyncio/unix_events.py", line 86, in add_signal_handler
    raise TypeError("coroutines cannot be used "
TypeError: coroutines cannot be used with add_signal_handler()`

**Comment by psidex** [comment]
Thanks for reporting this, should be fixed now
